config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'top/new'
  get 'tops/index'
  get 'tops/new'
  get 'users/index'
  resources :users
  resources :top , except: [:show]
  resources :likes
  root 'top#main'
  get 'top/main'
  post 'top/login'
  get 'top/error'
  get 'top/logout'
  get 'users/error'
  #get 'tweets/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_many :likes
  has_many :likes_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        user = User.find_by(uid: session[:login_uid])
        user.like_tweets << tweet
        redirect_to root_path
    end
    def destroy
        t = Tweet.find(params[:id])
        u = User.find_by(uid: session[:login_uid])
        t.likes.find_by(user_id: u.id).destroy
        redirect_to top_path
    end
end

app/controllers/top_controller.rb
require "bcrypt"
class TopController < ApplicationController
  def main
        if session[:login_uid] 
            @tweets = Tweet.all
            render "main"
        else
            render "login"
        end
  end
    def login
        #if params[:uid]=='kindai'and params[:pass]=='sanriko'
        #if BCrypt::Password.new(user.pass) == params[:pass]
        user=User.find_by(uid:params[:uid])
        if user and BCrypt::Password.new(user.pass) == params[:pass] 
            session[:login_uid]=params[:uid]
            redirect_to top_main_path
        else
            render 'error',status: 422
        end
    end
    def logout
        session.delete(:login_uid)
        redirect_to top_main_path
    end
    def new
       @tweet=Tweet.new 
    end
    def create
        t = Tweet.new(message: params[:tweet][:message])
        t.user=User.find_by(uid: session[:login_uid])
        t.save
        redirect_to top_main_path
        #top_main_path
    end
      def destroy
        t = Tweet.find(params[:id])
        t.destroy
        redirect_to top_main_path
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
   @user=User.new 
  end
  
  def create
    #文字列.include?(検索文字列)
    user_pass = BCrypt::Password.create(params[:user][:pass])
    if User.exists?(uid: params[:user][:uid])
      render 'error',status: 422
    else
      user = User.new(uid: params[:user][:uid], pass: user_pass)
      user.save
      #redirect_to '/'
      redirect_to top_main_path
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<<<<<<< HEAD
    <title>L5</title>
=======
    <title>L51</title>
>>>>>>> origin/main
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<h2>ログインエラー</h2>
<p>ユーザーIDまたはパスワードが正しくありません。</p>

<%= link_to 'ログイン画面に戻る', controller: 'top', action: 'main' %>

app/views/top/login.html.erb
<h2>ログイン</h2>
<%= form_with url: top_login_path, method: :post, local: true do |f| %>
    <%= f.label :uid, 'ユーザーID' %>
    <%= f.text_field :uid %>
    <%= f.label :pass, 'パスワード' %>
    <%= f.password_field :pass %>
    <%= f.submit 'ログイン' %>
<% end %>

<%= link_to '新規登録', '/users/new' %>
<%= link_to '登録一覧', '/users/index' %>

app/views/top/main.html.erb
<h2>ログイン中...</h2>
<% @tweets.each do |e| %>
    <p>
        <%= e.message %> (<%= e.user_id %>)
        <%= link_to '削除', "/top/#{e.id}", data: { turbo_method: :delete } %>
        <%= link_to 'いいね', likes_path(tweet_id: e.id), data: { turbo_method: :post } %>
        <%= link_to 'いいね削除', like_path(e), data: { turbo_method: :delete } %>
<<<<<<< HEAD
        <%= e.like_users.include?(User.find_by(uid: session[:login_uid])) %>
=======
        <%= e.like_users.include?(User.find_by(uid: session[:login_uid])) ? 'true' : 'false' %>
>>>>>>> origin/main
    </p>
<% end %>

<%= link_to '新規追加', '/top/new' %>
<<<<<<< HEAD
<%= link_to 'ログアウト', top_logout_path %>
=======
<%= link_to 'ログアウト', top_logout_path %>
>>>>>>> origin/main

app/views/top/new.html.erb
<h2>投稿する</h2>
<%= form_for @tweet , url: {action: :create} do |f| %>
  <%= f.label :message, 'メッセージ' %>
  <%= f.text_field :message %>
  <%= f.submit '投稿' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
    <p>
        ユーザID: <%= e.uid %><br>
        パスワード :<%= e.pass %><br>
        <%=link_to '削除', "/users/#{e.id}", data: { turbo_method: :delete } %>
    </p>
<% end %>

<%= link_to '新規追加', '/users/new' %>

<<<<<<< HEAD
<%= link_to 'ログイン画面に戻る', controller: 'top', action: 'main' %>
=======
<%= link_to 'ログイン画面に戻る', controller: 'top', action: 'main' %>
>>>>>>> origin/main

app/views/users/new.html.erb
<h2>新規登録</h2>
<%= form_for @user , url: {action: :create} do |f| %>
    <%= f.label :uid, 'ユーザID' %>
    <%= f.text_field :uid %>
    <%= f.label :pass, 'パスワード' %>
    <%= f.password_field :pass %>
    <%= f.submit '登録' %>
<<<<<<< HEAD
<% end %>
=======
<% end %>
>>>>>>> origin/main